version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_container
    ports:
      - "5423:5432"
    environment:
      POSTGRES_USER: vn_solutions
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: travel_agency_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
